---
title: "Simulation"
author: "Kari Norman"
date: "7/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(gstat)
library(sp)
```

Set simulation parameters
```{r}
#n for the n x n landscape grid
grid_size <- 100

#number of species
n_sp <- 5

#number of environmental variables
n_env <- 3
```

Create gridded environmental variables 
```{r}
# unconditional gaussian simulation of environmental variables using gstat
grid <- expand.grid(1:grid_size, 1:grid_size)
colnames(grid) <- c("x", "y")
 
# define the gstat object (spatial model)
spat_mod <- gstat(formula=z~1, locations=~x+y, dummy=T, beta=1, model=vgm(psill=0.025,model="Exp",range=5), nmax=20, data = grid)
 
# simulate three environmental variables
sims <- predict(spat_mod, newdata=grid, nsim=n_env)
 
# visualize
gridded(sims) = ~x+y
spplot(sims)

#convert to data frame of cells and simulated variables
env_data <- as.data.frame(sims)
```

Create dataframe of environmental suitability for each species 
```{r}
#function for getting a random range within an existing range
ran_range <- function(range){
  lower <- runif(1, range[1], range[2])
  upper <- runif(1, lower, range[2])
  
  return(data.frame(type = c("min", "max"), range = c(lower, upper)))
}

### get ranges for each species as two min and max columns ###
#get ranges for environmental variables 
env_ranges <- map(env_data %>% select(-x, -y), ~range(.x))

#dataframe of environmental decision rules
species_env <- map_dfr(1:n_sp, 
                       ~map_dfr(env_ranges, ~ran_range(.x), .id = "env_var") %>% 
                         mutate(species = paste0("spec", .x))
                       )

```

Create matrix species exclusion rules
```{r}
#random assignment of cooccurrence 
x <- sample.int(2, n_sp^2, TRUE) - 1
dim(x) <- c(n_sp, n_sp)
```

Identify potential species occupancy based on environmental requirements 
```{r}
#cases <- map(unique(species_env$env_var), ~substitute())
  
get_spec_occ <- function(species_name, data = env_data){
  data %>% mutate(!!species_name := case_when(sim1 > filter(species_env, species == species_name, env_var == "sim1", type == "min")$range &
                                        sim1 < filter(species_env, species == species_name, env_var == "sim1", type == "max")$range &
                                        sim2 > filter(species_env, species == species_name, env_var == "sim2", type == "min")$range &
                                        sim2 < filter(species_env, species == species_name, env_var == "sim2", type == "max")$range &
                                        sim3 > filter(species_env, species == species_name, env_var == "sim3", type == "min")$range &
                                        sim3 < filter(species_env, species == species_name, env_var == "sim3", type == "max")$range ~ 1,
                                      TRUE ~ 0)) %>%
    select(species_name)
}

occ <- map_dfc(paste0("spec", 1:n_sp), get_spec_occ)


```

Programatically generate case example
```{r}
labels <- c("low", "mid", "high")
breaks <- c(2, 4)

cases <- lapply(seq_along(breaks), function(i) {
  substitute(carb <= breaks[i] ~ labels[i], list(i = i))
})
cases <- append(cases, substitute(TRUE ~ labels[length(labels)]))
```

Features to add
* realistic environmental variable ranges













